from typing import Optional
from pydantic import BaseModel, Field


# ─────────────────────────────────────────────────────────────────────────────
# Request / Input models
# ─────────────────────────────────────────────────────────────────────────────

class StoryRequest(BaseModel):
    main_character: str = Field(
        default="Benny the Brave Bunny",
        description="Name and brief description of the main character",
    )
    supporting_characters: list[str] = Field(
        default_factory=lambda: ["Rosie the Fox", "Oliver the Owl"],
        description="Names and descriptions of supporting characters",
    )
    setting: str = Field(
        default="A magical forest with talking trees and glowing fireflies",
        description="Primary setting of the story",
    )
    moral: str = Field(
        default="True courage means helping others even when you're scared",
        description="The moral lesson to weave into the story",
    )
    main_problem: str = Field(
        default="A mysterious fog has covered the forest, and the animals can't find their way home",
        description="The central conflict or challenge the main character faces",
    )
    additional_details: Optional[str] = Field(
        default="Include a scene where the characters work together to solve a puzzle",
        description="Any additional plot details, themes, or scenes to include",
    )


# ─────────────────────────────────────────────────────────────────────────────
# Intermediate workflow data models
# ─────────────────────────────────────────────────────────────────────────────

class PageOutline(BaseModel):
    page_number: int
    scene_summary: str
    characters_present: list[str]
    emotional_tone: str
    plot_point: str  # what story milestone happens on this page


class StoryOutline(BaseModel):
    title: str
    target_pages: int = Field(ge=6, le=8)
    # Maps character name → detailed visual description for image consistency
    character_descriptions: dict[str, str]
    plot_summary: str
    page_outlines: list[PageOutline]
    # Populated during revision cycles
    revision_instructions: Optional[str] = None


class StoryPage(BaseModel):
    page_number: int
    text: str  # narrative text displayed on the page
    scene_description: str  # detailed visual description for the illustrator
    characters_present: list[str]
    emotional_tone: str
    image_prompt: str  # prompt sent to the image generation model
    image_url: Optional[str] = None  # filled in by ArtDirectorExecutor


class StoryDraft(BaseModel):
    title: str
    pages: list[StoryPage]
    moral_summary: str  # final page / closing moral statement
    cover_image_url: Optional[str] = None     # generated by ArtDirectorExecutor
    the_end_image_url: Optional[str] = None   # generated by ArtDirectorExecutor


class ReviewIssue(BaseModel):
    page_number: Optional[int] = None  # None means whole-story issue
    category: str  # "character_consistency" | "narrative_flow" | "age_appropriateness" | "art_text_alignment"
    description: str


class ReviewResult(BaseModel):
    approved: bool
    issues: list[ReviewIssue]
    revision_instructions: str  # actionable feedback for the Orchestrator


# ─────────────────────────────────────────────────────────────────────────────
# Final output model
# ─────────────────────────────────────────────────────────────────────────────

class StoryResponse(BaseModel):
    title: str
    pages: list[StoryPage]
    moral_summary: str
    cover_image_url: Optional[str] = None
    the_end_image_url: Optional[str] = None
    review_notes: str  # summary from the reviewer (even if approved)
    revision_rounds: int  # how many revision cycles were needed


# ─────────────────────────────────────────────────────────────────────────────
# SSE progress event model
# ─────────────────────────────────────────────────────────────────────────────

class ProgressEvent(BaseModel):
    executor_id: str
    status: str  # "started" | "working" | "completed" | "revision"
    message: str
    detail: Optional[str] = None
